### ISSUE TITLE
Low res - DICUI 1.10 opens with buttons off screen

### ISSUE THREAD

**Issue by avieros** [SabreTools/DICUI#109]
Hi Guys,

when i RDP into my pc - it's at resolution 1366x768. When DICUI opens it opens with main menu and close/minimise etc off-screen. To close, I need to right-click on taskbar icon, or force close. I can drag and move the log box, so if i hide the log, and force close or If I force close and hide log file via config (OpenLogWindowAtStartup" value="False) - DICUI opens centrally on-screen.

So i think the placement logic based on resolution needs some additionally testing based on low-res environments.

**Comment by mnadareski** [comment]
Assigning this to @reignstumble since he has more experience with both UI and accessibility at the moment.

**Comment by ajshell1** [comment]
![offscreen](https://user-images.githubusercontent.com/11084981/48643973-3acf1a80-e9af-11e8-8e3a-597a99adf16c.png)
Here's an example I took on a virtual machine.

**Comment by mnadareski** [comment]
Hey @avieros and @ajshell1 it's been a ridiculously long time since this came up. Is this still an issue or needed to be addressed? I don't think there's any way to shrink the UI at this point and closing the log is about the best solution. I won't close this yet, but I think this will end up as a wontfix.

**Comment by avieros** [comment]
It still happens when I RDP, but local access isn't an issue. Probably
easier for me to change my habits, than for you to change code ;)

**Comment by mnadareski** [comment]
If this persists as an issue in the future, this can be reopened. For now, I'm closing as wontfix, pending saving log to file as an additional aid to this.
