### ISSUE TITLE
BD-Video dumping

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#114]
File this under far-off future wish list if necessary.
https://arstechnica.com/uncategorized/2007/02/8837/
http://forum.doom9.org/showthread.php?p=949426#post949426

**Comment by mnadareski** [comment]
There have been encrypted BD-Video discs successfully dumped with DIC via DICUI, so I think that covers this. There was no particular commit that made it work, just verified semi-recently.
