### ISSUE TITLE
Update Ring Code Guide template

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#115]
General ring code that should cover everything except Xbox series.
*Data side:
**Mastering Code (laser branded/etched):
**Mastering SID Code:
**Toolstamp or Mastering Code (engraved/stamped):
**Mould SID Code:
*Label side:
**Mould SID Code:

Xbox series:
*Data side:
**Mastering Code (laser branded/etched):
**Mastering SID Code:
**Toolstamp or Mastering Code (engraved/stamped):
**Mould SID Code:
*Label side:
**Mastering Code (laser branded/etched):
**Mastering SID Code:
**Toolstamp or Mastering Code (engraved/stamped):
**Mould SID Code:

**Comment by ajshell1** [comment]
You need to include "Additional Mould Text" as well. It's really rare on discs, but it does appear every now and then, and I think we should include it.

**Comment by mnadareski** [comment]
Fixed in https://github.com/SabreTools/DICUI/commit/eb4904afb4e1d13daecf45a48eb50a581c9c4108 and I forgot to tag it. This should all be taken care of now.
