### ISSUE TITLE
PlayStation 2: "CD-Rom (Unlicensed)" option

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#123]
Please, with /sf flag

**Comment by mnadareski** [comment]
"Unlicensed CD-ROM" is not a valid format and I don't intend on adding that. Can you explain why the `/sf` flag is needed for these discs?

**Comment by dizzzy77** [comment]
It's required for dumping unlicensed PS2 discs properly due to some datel fuckery http://forum.redump.org/post/60119/#p60119
http://forum.redump.org/post/60919/#p60919

it's the only dumping settings that redump accepts for dumping unlicensed PS2 discs, as they won't dump with normal parameters

**Comment by mnadareski** [comment]
I feel like this is probably a small enough zone where these unlicensed discs don't really warrant a separate profile. I'd suggest adding a note to add the custom parameter when dumping, if possible. If these discs are more common than this, I will consider a "PS2 Unlicensed" or something similar.

**Comment by dizzzy77** [comment]
Not sure if this changes your mind but there are a few hundred unique discs that could be dumped with this method. Maybe DICUI could detect "BIG.DAT" in root and automatically add this flag.
