### ISSUE TITLE
DICUI doesn't support non-latin characters in volume labels

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#129]
when trying to load a DVD-Video in DICUI it freezes in "waiting for media state". Presumably because the disc title is in japanese.

**Comment by dizzzy77** [comment]
Seems to be working suddenly, might require more troubleshooting...

**Comment by mnadareski** [comment]
DIC and therefore DICUI should be unicode-compliant. This sounds like a drive error, not a program one. If this is reproducible, please include steps that can be used.

**Comment by mnadareski** [comment]
It turns out that DIC is NOT unicode-compliant. This is an issue with the base application, but there might be a way of auto-sanitizing the input from anything outside of the latin set to be latinized. Easier if sarami does it in DIC first.

**Comment by mnadareski** [comment]
We have not been able to confirm this issue properly and DIC still is not usually releasing the Unicode builds. This one is out of DICUI's league in terms of fixability.
