### ISSUE TITLE
Dreamcast Dumping

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#13]
Not sure how to implement this, will take a bit of research, trial and error I suppose. Not high on the list IMO, but perhaps let's put it on the radar http://wiki.redump.org/index.php?title=GD-Rom_Dumping_Guide

**Comment by mnadareski** [comment]
This is *technically* supported using the "gd" command, and by using custom parameters with the "swap" command. Otherwise, it's going to be a bit before this can get in.

**Comment by mnadareski** [comment]
I'm calling this one set since the `gd` command does this as it should. The new profile for CD-ROM for the low density area should also be sufficient.
