### ISSUE TITLE
DICUI doesn't detect the difference between single and dual-layer BD-ROMs

### ISSUE THREAD

**Issue by icup321** [SabreTools/DICUI#130]
So I just dumped a PS4 game and I noticed that when you select Sony PlayStation 4 in the disc types, it doesn't detect whether or not it is single layer (25 GB) or dual layer (50 GB) so it defaults to single layer and labels it as such in the disc submission output file. This is also an issue with all other form of dual-layer Blu-Ray discs from console games to regular Blu-Ray video discs.

**Comment by mnadareski** [comment]
It appears that DIC itself does not output any layerbreak information in the `_disc.txt` file, so for the time being, this is a wontfix.

**Comment by mnadareski** [comment]
Seems like I lied, this *was* something I ended up being able to do without DIC doing it for me. This has been addressed in https://github.com/SabreTools/DICUI/commit/043c0eff1cef609ad1f9003f5a9856fd08fe2503
