### ISSUE TITLE
LibCrypt not detected

### ISSUE THREAD

**Issue by ajshell1** [SabreTools/DICUI#134]
A friend of mine sent me a PAL PSX disc a while back. The DB says that it has libcrypt:
http://redump.org/disc/1063/
DICUI 1.11 says it doesn't

Title: (REQUIRED)
Disc Number / Letter: (OPTIONAL)
Disc Title: (OPTIONAL)
System: Sony PlayStation
Media Type: CD-ROM
Category: Games
Region: World (CHANGE THIS)
Languages: Klingon (CHANGE THIS)
Disc Serial: (REQUIRED, IF EXISTS)
EXE Date: 
Ringcode Information:
	Mastering Ring: (REQUIRED, IF EXISTS)
	Mastering SID Code: (REQUIRED, IF EXISTS)
	Mould SID Code: (REQUIRED, IF EXISTS)
	Additional Mould: (REQUIRED, IF EXISTS)
	Toolstamp or Mastering Code: (REQUIRED, IF EXISTS)
Barcode: (OPTIONAL)
Error Count: 0
Comments: (OPTIONAL)
Contents: (OPTIONAL)
Version: (REQUIRED, IF EXISTS)
Edition/Release: Original (VERIFY THIS)
EDC: Yes
Anti-modchip: No
LibCrypt: No
Primary Volume Descriptor (PVD):

0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 31 39 39                199
0330 : 39 30 36 31 38 30 30 33  30 30 30 30 30 00 30 30   9061800300000.00
0340 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 00 30   00000000000000.0
0350 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 00   000000000000000.
0360 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30   0000000000000000
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

Cuesheet:

FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 1).bin" BINARY
  TRACK 01 MODE2/2352
    INDEX 01 00:00:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 2).bin" BINARY
  TRACK 02 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 3).bin" BINARY
  TRACK 03 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 4).bin" BINARY
  TRACK 04 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 5).bin" BINARY
  TRACK 05 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 6).bin" BINARY
  TRACK 06 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 7).bin" BINARY
  TRACK 07 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00
FILE "V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 8).bin" BINARY
  TRACK 08 AUDIO
    INDEX 00 00:00:00
    INDEX 01 00:02:00

Write Offset: -572

DAT:

<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 1).bin" size="455502432" crc="cb2268cc" md5="2034a0b987d27c5b223a19ec7d865674" sha1="1c7e4f7622b48f8932bb27d740744d0479d02666" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 2).bin" size="16104144" crc="6696ff0e" md5="4dd0fcdf534ab19bc95802c5461fc7b6" sha1="4cfbfeeb9c2b6c7d48f83ac81030a6109928d6b2" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 3).bin" size="42721728" crc="5d270e96" md5="6b16eeac23b5609fd2b58e6b662ccb71" sha1="2645edb35ead34cc3af83b1d9c0ba6f1591fe3d0" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 4).bin" size="33866448" crc="69e9c3ea" md5="655fff70290cd0bad890dce9bb9ee4be" sha1="f2854d0e94c0923a2dc1f37fa644e33d386610ce" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 5).bin" size="36604176" crc="0e16c943" md5="7a4987333c1af0cd38b3bb294a69e7c3" sha1="0e750380ab0fad3a7acc7dca42094262ab2b8c5c" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 6).bin" size="47738544" crc="959166bd" md5="90db1323815085fb7547cb147f808254" sha1="775f3912ae4f44488fd9e43e4bb1a04c9761e3a3" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 7).bin" size="36380736" crc="978643e2" md5="ca8f6512052e8331bc68ffa2e00028cb" sha1="4161e2affb7b047eb0f8340e4c575d7662d150cb" />
<rom name="V-Rally - Championship Edition 2 (Europe) (En,Fr,De) (Track 8).bin" size="32986800" crc="c317d4be" md5="b4635067b7e9d9cf9aadabe5c7a0809b" sha1="1ccdea80b0e2e26b872e60bd7602bc635ba037f3" />

**Comment by mnadareski** [comment]
Due to enhancements in BurnOutSharp, it should be now possible to have more accurate detection of LibCrypt. It will be added momentarily.
