### ISSUE TITLE
Add Jaguar CD as a dumping option

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#140]
uses the same regular CD commands, nothing special for being multisessional

**Comment by mnadareski** [comment]
Just 100% verifying here, it doesn't require the `/ms` flag?

**Comment by mnadareski** [comment]
Adding it same as Audio CD has been done on https://github.com/SabreTools/DICUI/commit/7ba04e63c77106bf60c47e3130e2aec4d80e29a9

Still waiting on a response to see if `/ms` is necessary.

**Comment by mnadareski** [comment]
The `/ms` flag seems nonfunctional at this time. Closing this unless it comes up again.
