### ISSUE TITLE
Detect System by inspecting disc filesystem contents 

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#142]
#49 requested detect disc type and also mentioned detect system.

detect disc type has been added in #73 

detect system would be very useful for those platforms it is possible for.

Below is edited version of what is at https://github.com/SabreTools/DICUI/issues/49#issuecomment-397791742 thanks @dizzzy77 

Work in progress guide:

## Sony

- PS1: 
  - has a `SYSTEM.CNF` that contains `BOOT` line
- PS2: 
  - has a `SYSTEM.CNF` that contains `BOOT2` line
- PS4
  - has `PSLogo.ico` in root

## Sega
- Saturn: not sure
- Mega/Sega CD: 
  - has one of:
    - `0LOADER.BIN`
    - `FILESYSTEM.BIN`
    - `IP.BIN`
    - `IPL.BIN`
    - `MAINOS.BIN`
    - `SHELL.BIN`
    - `SP.BIN`
    - `SP_AS.BIN`
  - or has all of:
    - `ABS.TXT`
    - `BIB.TXT`
    - `CPY.TXT`
- Dreamcast: 
  - is a GD-Rom
  - has a `IP.BIN`

## Microsoft - not sure about these
- Xbox:
- Xbox 360:
- Xbox One:

## Misc
- Vtech Vsmile Pro
  - Has a `0SYSTEM` in the root
- Audio CD / Jaguar CD
  - all Audio tracks

**Comment by mnadareski** [comment]
Clarification question: For Sega CD, are *all* of those files supposed to be present? Or is it just some of them?

**Comment by gingerbeardman** [comment]
Good question! 

Any one of them.

But... it's an incomplete list. Have added a few more to it now.

**Comment by mnadareski** [comment]
Even further clarification: Before, the files like `IP.BIN` for SCD were all listed as being under a `_BOOT` directory. Is this true for those files or any of the others listed?

**Comment by gingerbeardman** [comment]
I read that somewhere but I've been unable to verify it myself. I've only found those files at root level.

**Comment by mnadareski** [comment]
I'm going to close this since the core of the request has been fulfilled a few times now. If more systems come up, they should be submitted as separate issues.
