### ISSUE TITLE
Option to issue reset command after each dump

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#143]
My Plextor PX-716UF requires a hard reset after each rip in order to get consistent results.

I do this: `DiscImageCreator.exe reset E`

But it would be great if there was an option to do this from DICUI or as part of the dumping.

(`reset` is only applicable to Plextor drives)

**Comment by gingerbeardman** [comment]
See https://github.com/saramibreak/DiscImageCreator/issues/28 and https://github.com/saramibreak/DiscImageCreator/issues/27

**Comment by mnadareski** [comment]
Slightly related note: if you have an issue specifically with how DICUI does things and what DIC is doing, only open an issue against DICUI. Sarami doesn't care about DICUI and has said he has nothing to do with it.

**Comment by gingerbeardman** [comment]
OK, will do what I can to avoid Drama
