### ISSUE TITLE
Wrong error message when system/type is unknown, but "start dump" is clicked

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#145]
Using latest AppVeyor build.

- System == unknown
- Type == unknown

Actual
- If I scan for disks, start dumping button becomes enabled
- If I press it, I get the error "a complete dump already exists"
- But there was no existing dump

Expected
- I would expect to get the error "system and disc type are not set"
- Maybe "start dump" should not be enabled in this situation?

Screen
![Screen shot 2019-06-17 at 20 56 18](https://user-images.githubusercontent.com/49612/59632799-f7a27900-9142-11e9-8e18-db2ed6df772c.png)

**Comment by mnadareski** [comment]
Made sure that the selected item is not NONE before re-enabling the button.
