### ISSUE TITLE
Disc title parsed as "Version 1" when it is in fact DEMO_ONE 

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#147]
Demo One (Version 1)
http://redump.org/disc/531/

My logs:
http://www.mediafire.com/file/2io9ke08y1cmei6/DEMO_ONE.logs.7z/file

I think maybe Version from CNF file is being entered against the wrong field?

**Comment by mnadareski** [comment]
It's pulling that info from the page you linked to, and "Version 1" should be pulled in as the edition or release. It's not grabbing it from the CNF at all since PSX games don't have a version in there, unlike PS2 games.

**Comment by gingerbeardman** [comment]
OK, thanks for the info about PS1 vs PS2 CNF! I didn't know that.

Do you see the problem?

**Comment by mnadareski** [comment]
I finally figured out where your confusion was coming from. There's 2 separate things going on here:
- DICUI is pulling the name `Demo One (Version 1)` with the assumption that items in parenthesis are not part of the title, and indicate disc number and title. Unfortunately, this is a corner case so it's not easily fixed.
- Your understanding of "Disc Title" is different than the Redump usage. Disc title in Redump is the title printed on the disc, not the volume title. Volume title doesn't get saved in Redump. From your logs, you put the volume title as the Disc Title.

**Comment by gingerbeardman** [comment]
Oh! Thanks, I'll try to not do that in future
