### ISSUE TITLE
EDC / NoEDC error on PS1 games

### ISSUE THREAD

**Issue by antonioocera** [SabreTools/DICUI#148]
As you can see from this http://forum.redump.org/post/70577/#p70577 http://redump.org/disc/7925/ and many other logs from the Redump forum, the submissionInfo file reports EDC where actually the game is NoEDC, and viceversa. This cause a lot of confusion when submitting new dumps, of course.

**Comment by gingerbeardman** [comment]
I am the dumper of that game. I was using an old version of DICUI at that point.

I'll dump it again so we can see what the latest version does. If that fixes things, I am happy to redump affected games.

Cheers!

**Comment by antonioocera** [comment]
I've seen other logs from the forum and actually the submissionInfo file is always reporting EDC = YES.
You don't need to redump anything, you can just manually check the .bin file with edccchk just to be sure. I think it's just a small error for the submissionInfo file, that can be easily fixed hopefully. If you can test the latest version can be better though.

**Comment by gingerbeardman** [comment]
Great news it's just an error in the summary.

**Comment by mnadareski** [comment]
If you can provide the `_EdcEcc.txt` or `_EccEdc.txt` file from one of those dumps, I'd appreciate it. Since DICUI is just trying to use the DIC outputs to determine EDC state, it's somewhat inaccurate as the current method just uses the number of EDC-related errors as the metric.

**Comment by gingerbeardman** [comment]
Here we go, I redumped the game SLPS-00373 using the latest AppVeyor build of DICUI (ie. DIC 20190629 193630).

[disc.img_EccEdc.txt.zip](https://github.com/SabreTools/DICUI/files/3446559/disc.img_EccEdc.txt.zip)

**Comment by mnadareski** [comment]
Thank you, I think I need to look into this a little more since it appears that more info might be needed to figure out the EDC status.

**Comment by gingerbeardman** [comment]
Let me know if I can help more.

**Comment by mnadareski** [comment]
From @superg elsewhere:
```
EDC yes / no for PlayStation: you have to iterate over each mode2form2 cd sector and check if edc field is zero
EDC - No: all mode2form2 edc fields are 0
EDC - Yes: all mode2form2 edc fields are non zero (technically zero edc can still be a legit case so I think that all sectors have to be scanned)
```
