### ISSUE TITLE
Unexpected behaviour when "Disc Not Detected"

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#149]
Sometimes I get "Disc Not Detected" and the app will enter this state:

- the Start Dumping button is active
- clicking it gets the "no disc" alert which makes no sense

![Screen shot 2019-06-20 at 15 33 45](https://user-images.githubusercontent.com/49612/59860773-708a1680-9377-11e9-8aab-f5e0e86878b6.png)

Currently I have come across a handful of disc that appear like this:

- Archer Maclean's 3D Pool
- Tail of the Sun
- Sentinel Returns
- Speed Freaks

**Comment by mnadareski** [comment]
If Windows can't see that there's a disc there, but there's actually a disc in the drive, that warning is thrown just in case you did actually select an empty drive. It's just a precaution, especially for some Macintosh and other systems like 3DO.

**Comment by gingerbeardman** [comment]
OK thanks

It's odd that sometimes the same disc is recognised and others not in my Windows install.
