### ISSUE TITLE
DVD-Video file hash output in wrong format.

### ISSUE THREAD

**Issue by wiggy2k** [SabreTools/DICUI#158]
not a mjor issue by any means but:
Just dumped 10 DVD-Video discs and the file hash output in submission info was in the format of 

Size & Checksum:
	Size: 4056061952
	CRC32: ff6cb403
	MD5: f4cd808ab95ca5e8036ddee6335b0cb1
	SHA1: 51cbfc0ef9113ad106a953ba8c3c176ad38520d8

rather than the properly formatted:
     <rom name="DM050830.iso" size="4056061952" crc="ff6cb403" md5="f4cd808ab95ca5e8036ddee6335b0cb1" sha1="51cbfc0ef9113ad106a953ba8c3c176ad38520d8" />

**Comment by mnadareski** [comment]
As noted elsewhere, this is intentional since the Redump submission form (which the submission info output is tailored for) uses this odd format for DVD-5 and DVD-9 compared to the regular field for CD-based stuff. Once Redump changes this, this will change as well.
