### ISSUE TITLE
Dialog for Collection of Submission details to store in the submission.txt

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/DICUI#159]
It would be great if upon successful completion of a dump, the program could pop up a dialog box in order to collect optional submission information, that once saved, is then added automatically to the submission.txt file.  This could include the elements that aren't dumped with the program:
Title, Foreign Title, Region, Language Information, Disc Serial, Ringcode Information, etc.

Essentially, the elements that need to be filled in later.  

I believe this would streamline the dumping and data collection process which would make submissions easier for users.

**Comment by Whovian9369** [comment]
I'd say it should be Opt-In personally, for people like me that would honestly prefer to fill out the file "properly" or something.

**Comment by sadikyo** [comment]
That's why I say optional - you can bypass that window either in part or in full if people don't want to do it.  And if it is created - not all fields should be required anyway, because they will differ both by media type or by what information the user has.

A setting to turn on or off the dialog, would be fine, if people don't want to use it.

**Comment by mnadareski** [comment]
WIP, see branch
