### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#16]
A single downloadable EXE that makes it ever easier.

**Comment by mnadareski** [comment]
I'm separating this into two different tasks.

**Comment by Jakz** [comment]
Do we really need this? I mean, there's nothing to be installed since it's distributed as an archive. In addition having portable applications is usually a better solution (nothing installed on system preferences and such).

**Comment by mnadareski** [comment]
I'm going to agree with that sentiment for now. Especially with how the release cadence and testing is, installing might be a bad idea. This will be closed as a wontfix for now, but we can always reopen in the future if this tool *really* becomes that necessary to install.
