### ISSUE TITLE
WinXP DICUI

### ISSUE THREAD

**Issue by Polymega** [SabreTools/DICUI#160]
Hi DICUI team, 

Forgive my question here, as I know DICUI is meant for Win7 and above. 

I have a prototype PS2 disc for Silent Hill 2 (more specifically, a PS2 "DVD-R for Authoring" disc).

![image](https://user-images.githubusercontent.com/27395260/64930116-89ca2400-d7fb-11e9-9646-1849d6712370.png)

This disc cannot be read/detected in my Win7 desktop. The disc _can_ be read, however, in my wife's old WinXP laptop. I'd like to properly extract/archive the contents of this disc through DICUI but it seems my wife's WinXP laptop is the only way I'd be able to do so. 

Is there any possibility to compile the project for WinXP usage?

**Comment by mnadareski** [comment]
Speaking as the only person currently maintaining this project, I do not want to figure out what effort would be needed to go into converting this to .NET 4 or earlier to run on XP. I'm sure it's possible, but it's not worth it for me. You have a couple of alternatives:
1) Still use DICUI on a modern computer with a DIC-compatible drive. Even if the disc can't be detected, there's a nonzero chance it can be read. Similar situation to things like Macintosh CDs.
2) Dump the disc on an older machine using DIC (just the CLI version), copy the output files as-is to a modern machine, and then run DICUI-Check against the contents. This will allow you to dump your disc in an environment that works for you as well as getting some of the automation from DICUI for gathering the output information.

**Comment by Polymega** [comment]
Thanks for the follow-up, @mnadareski .

> 1. Still use DICUI on a modern computer with a DIC-compatible drive. Even if the disc can't be detected, there's a nonzero chance it can be read. Similar situation to things like Macintosh CDs.

I previously tried this and unfortunately it did not work for me; DICUI still couldn't detect the disc on my Win7 desktop. Assuredly because the drive itself is not compatible. 

> 2. Dump the disc on an older machine using DIC (just the CLI version), copy the output files as-is to a modern machine, and then run DICUI-Check against the contents. 

Thank you for this recommendation. May I ask you to link me to DIC (CLI version)? Also, is DICUI-Check different than running the normal DICUI.exe binary?

**Comment by mnadareski** [comment]
If the drive is compatible with an older machine, it will probably be compatible with a newer machine with an adapter, but I digress.
For links to DIC, please see the main GitHub page, I have a link to the base project there. Or just use the version that's bundled with DICUI, it's the same program, I don't modify it in any way.
DICUI-Check is slightly different since, instead of being able to put in the disc type and system before dumping, you need to specify them in the commandline option so that it knows how to read the DIC output files.

**Comment by Polymega** [comment]
Perfect. I'll give this all a go soon. Thank you again. 

> If the drive is compatible with an older machine, it will probably be compatible with a newer machine with an adapter, but I digress.

My wife would be mad if I ripped her DVD drive from that old laptop (she still uses it!).

**Comment by janslavik85-ui** [comment]
Hello @Polymega do you mind to share with me the story, how this rare item ends in your hands? I am SH2 fan, and in last years, also a collector and I am really interested in your story. Thank you

**Comment by mnadareski** [comment]
@janslavik85-ui this is not the place to hold such discussions. Please do not do this again.

**Comment by janslavik85-ui** [comment]
> [@janslavik85-ui](https://github.com/janslavik85-ui) this is not the place to hold such discussions. Please do not do this again.

My apology
