### ISSUE TITLE
Playstation 4 Detection

### ISSUE THREAD

**Issue by avieros** [SabreTools/DICUI#164]
Every Playstation 4 (retail) disc contains the following:

1. Drive Label = PS4VOLUME
2. directory bd which contains param.sfo
3. directory license which contains rif
4. directory app which contains "XXXXXXXX" which is actually the disc serial aka CUSA00112 - this will contain app.pkg
5. directory PS4 which contains dir UPDATE which contains PS4UPDATE.PUP

_**i have not come across a disc that deviates from this layout**_

**Comment by Whovian9369** [comment]
To use a PS4 disc that I dumped (which I have not gotten into Redump yet, I don't believe...) as an example:

```
$ file TWDS01.iso 
TWDS01.iso: ISO 9660 CD-ROM filesystem data 'PS4VOLUME'
```
Detecting the `PS4VOLUME` media label might be an alright way to detect these discs?

Just a specific file list from the disc, in this case:
```
app/CUSA01019/app.pkg
bd/param.sfo
license/rif
PS4/UPDATE/PS4UPDATE.PUP
```
