### ISSUE TITLE
DICUI exception on Server 2012 R2

### ISSUE THREAD

**Issue by avieros** [SabreTools/DICUI#165]
When clicking "Start Dumping"
This will trip an exception, 
`DiscImageCreator.exe has stopped working
Problem signature:
  Problem Event Name:	BEX
  Application Name:	DiscImageCreator.exe
  Application Version:	0.0.0.0
  Application Timestamp:	5d173f33
  Fault Module Name:	ucrtbase.DLL
  Fault Module Version:	10.0.14393.2990
  Fault Module Timestamp:	5caeb859
  Exception Offset:	000872b2
  Exception Code:	c0000409
  Exception Data:	00000005
  OS Version:	6.3.9600.2.0.0.400.8
  Locale ID:	1033
  Additional Information 1:	928f
  Additional Information 2:	928fe420eb116d460f9da463803fa911
  Additional Information 3:	5095
  Additional Information 4:	50955315691ba9c0230e38bcffab0efe
`
Can click "Close the program" and dumping will continue without issue,..

**Comment by mnadareski** [comment]
Seems like this might be an issue with DIC itself. Sarami might be able to help if you reach out on the base project.
