### ISSUE TITLE
A Safedisc disc using in 1.14 it won't find the copy protection like 1.13 does

### ISSUE THREAD

**Issue by ToeKnee007** [SabreTools/DICUI#168]
A Safedisc disc using in 1.14 it won't find the copy protection like 1.13 does. When clicking "Scan for protection" I get the following

```
Scanning for copy protection in Y
Detected the following protections in Y:

Path could not be scanned!
```

**Comment by mnadareski** [comment]
Fixed in https://github.com/SabreTools/DICUI/commit/22ffda4b5a1253461f1493fb58d2ba489ee42c33
