### ISSUE TITLE
Change Languages field to combobox with checkable items or dropdown list

### ISSUE THREAD

**Issue by pool7** [SabreTools/DICUI#170]
Low priority; just a suggestion.
In the Disc Information screen that appears right after a successful dump, the Languages field is a 1-item height scrollable list, which is uncomfortable to use and read. I'd like to suggest changing it to a combo box with items that can be checked or a similar style dropdown list.

**Comment by mnadareski** [comment]
This issue is a symptom of a larger issue: the only current active developer (myself) does not know how to do proper UI design. Anyone who can help with updating the UI would be greatly appreciated.
