### ISSUE TITLE
Eject before Disc Information?

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#173]
I cannot get the disc information before the disc is ejected.

It would be nice if it ejected before Disc Information form was presented.

**Comment by mnadareski** [comment]
If you're talking about the auto-eject option, then I suppose you're right, but there's nothing stopping you from ejecting the disc at that point. All of the protection scan and the like will have already been done if the disc info window comes up. That's why it's timed for that point.

**Comment by gingerbeardman** [comment]
Thanks! Good to know that me manually ejecting it at that point is not a bad thing.
