### ISSUE TITLE
Header is not copied to submission info for Dreamcast discs.

### ISSUE THREAD

**Issue by wiggy2k** [SabreTools/DICUI#174]
The header for DC discs (like other sega systems) should be included in the submission info, currently it is not.
 0000 > through to 00FF, or in this this case lines 3 to 18 (inclusive) of the main info txt file contain the header in the correct format.

**Comment by wiggy2k** [comment]
[POWER_SMASHtest.zip](https://github.com/SabreTools/DICUI/files/3996267/POWER_SMASHtest.zip)
Example logs

**Comment by mnadareski** [comment]
Addressed in https://github.com/SabreTools/DICUI/commit/7dd6db66eeef8a93ac3a059035c4c7fd29ea610a
