### ISSUE TITLE
Set region/language automatically using PlayStation game serial

### ISSUE THREAD

**Issue by gingerbeardman** [SabreTools/DICUI#175]
It would be great if region and/or language could be automatically set using the PlayStation game serial.

eg. 花と龍 = Hana to Ryuu = SLPS 01532

**NTSC-U**
- SCUS
- SLUS

**PAL-E**
- SCES
- SLES

**NTSC-J** 
- SCPS
- SCPM
- SLPS
- SLPM
- PBGP
- CZP2
- HSN
- GN

**NTSC-K**
- SCKA
- SLKA

**NTSC-C**
- SCAJ
- SCCS

(incomplete list)

See: http://psxdatacenter.com

**Comment by mnadareski** [comment]
Since disc labels are consistent, I'll be using the executable names to try to figure this out.

**Comment by gingerbeardman** [comment]
Thanks for this!
