### ISSUE TITLE
Cursor Jumping Around and Adding Spaces when Renaming Target Directory

### ISSUE THREAD

**Issue by dizzzy77** [SabreTools/DICUI#176]
See vidya: https://drive.google.com/file/d/1nsWjqZz9nuxAR1g_vSYkO9oXBHMPHhHu/view?usp=sharing

Version: DICUI_1.15-net472 with latest DIC

**Comment by dizzzy77** [comment]
I should note this is a long-time issue for me not unique to the current build.

**Comment by wiggy2k** [comment]
^ a quick way you can replicate the jumping to the start of the field by tying to insert and ampersand to the folder name.
trying to add other invalid characters like a "  can sometimes make DICUI Crash altogether.
