### ISSUE TITLE
Improve PS1/PS2 region detection

### ISSUE THREAD

**Issue by Landcross** [SabreTools/DICUI#186]
Recently this issue was incorporated and closed: https://github.com/SabreTools/DICUI/issues/175 with commit https://github.com/SabreTools/DICUI/commit/cb39599a46f50e67a64d2f420bc1c00ba1cd25e7

But the logic can be improved. Quite a few serial types are not included, and a bunch of serial types that are included have no reason to be. 

It's probably easier to look at the third letter: A = Asia, C = China, E = Europe (any specific region unknown), K = Korea, P = Japan, U = USA. Except when the id starts with a P. Then it's very different, but those are not very common anyway.

pbgp, czp2, hsn and gn can be removed anyway, afaik those are only packaging serials.

**Comment by mnadareski** [comment]
Do you mind clarifying for the `P` cases? Or if you happen to have a link that describes this further I'd appreciate it

**Comment by Landcross** [comment]
The P serials can be looked up on Redump, PAPX, PBPX, PCPX, PDPX and PEPX. PAPX and PXPC can somewhat be assumed to be Japanese, but the other ones. I doubt it's worth making a logic for those because it's either guesswork or it won't even barely be used anyway.

**Comment by RibShark** [comment]
`J` can sometimes also be used for Korea (and maybe other asian discs too?)
Not really something that can be useful for redump, but 2nd character can be `C` for Sony published software (occasionally `I` in Japan), and `L` for 3rd party software. 4th character is usually `S` for most full games, `D` for demos and `M` for Japanese/Asian titles that do not use Sony's own distribution network.

**Comment by mnadareski** [comment]
Some of that other information may be useful to set the disc type (such as Game or Demo). I'll have to look a little further into the `P*` serials before determining if those are worthwhile to add in the check. Definitely have to make sure the first character is `S` in the serial before trying to get the region from it, at the very least.
