### ISSUE TITLE
DICUI holds *.sub file handle until exit or another dump start

### ISSUE THREAD

**Issue by superg** [SabreTools/DICUI#191]
After the dump is successful sometimes I rename / move the directory without closing DICUI and the new versions keeps me from doing that, quite annoying.

**Comment by mnadareski** [comment]
Another fun one I see. Not sure where that would happen, but it's probably in submission gathering. Here's hoping it's an easy catch.

**Comment by mnadareski** [comment]
I'm going to hazard a guess that, in line with the other 5 issues opened, this pertains to PSX games. If that's the case, it's a bug in https://github.com/mnadareski/BurnOutSharp . I'll open the bug there for when I can fix it and link it back here.

**Comment by superg** [comment]
Yeah, it's PSX games but it didn't happen earlier. I recall that some time ago you mentioned that you were looking into libcrypt so I thought you parse *.sub file directly to detect libcrypt.

**Comment by mnadareski** [comment]
Yes, it does parse the `.sub` files directly, but the actual code for detecting LibCrypt lives in the protection detection library. Which is what I mentioned above.

**Comment by superg** [comment]
Oh, I didn't realize that BurnOutSharp is also yours, somehow thought it's some external closed source library.

**Comment by mnadareski** [comment]
I just pushed the change to BurnOutSharp that makes the code a little more safe when it comes to checking for LibCrypt. Turns out the 1:1 code port I did before was a bit too simplistic and assumed the original code was reasonable. It wasn't. Once the package gets on NuGet, I'll update DICUI accordingly.
