### ISSUE TITLE
Failed to extract exe date from [PSX] Megatudo 2096 (Japan) game

### ISSUE THREAD

**Issue by superg** [SabreTools/DICUI#192]
SYSTEM.CNF:
BOOT=cdrom:\SLPS_004.35

Note that there is no semicolon after.

**Comment by mnadareski** [comment]
Yet another pattern for `SYSTEM.CNF` files. I swear there was no quality control on those...

**Comment by mnadareski** [comment]
Okay, harder than I thought. I may need to triple check what other cases there were that could contain info *after* the semicolon since I have a check for it in-code. I may just have to do a trim or some stupid stuff like that...
