### ISSUE TITLE
[Problem] DICUI fails to check for protection on a specific PC disc

### ISSUE THREAD

**Issue by icup321** [SabreTools/DICUI#195]
So I am trying to dump a PC disc which contains graphic drivers, game demos, resources, etc. for Hercules graphic cards. After I successfully dump it with DIC, I think DICUI freezes while trying to scan the disc for protection, there are no errors printed in DICUI's log so I can't tell, but after a while DICUI gives up and just closes itself. And no, I am not using the .NET Core 3.0 build which has protection scanning broken, this is the .NET Framework build I am using.

**Comment by mnadareski** [comment]
Possibly fixed in https://github.com/SabreTools/DICUI/commit/6bda7b35a26548d0451381d33e16d438cdf7a440 please check with latest build

**Comment by icup321** [comment]
I just tested it, thanks to the progress bar I found out it was my plextor drive that was causing it to hang, all I had to do was take out the disc and let the plextor cool off for a while, then reinsert it and let it slowly scan the rest of the files. Closing this issue now.
