### ISSUE TITLE
"Drive is not updated to the latest firmware" error

### ISSUE THREAD

**Issue by yudilevi2** [SabreTools/DICUI#198]
Hi,

When clicking the 'start dumping' button, DICUI reports an error that the drive firmware isn't updated to the latest version even though it does.

Version: DICUI 1.16
Drive Model: Plextor PX-755UF
Drive Firmware: 1.08

Thanks

**Comment by mnadareski** [comment]
This means that DIC is saying the firmware is out of date. If you think it's an error, report it on DIC's GitHub or on the Redump thread. This is not a UI issue.

**Comment by mnadareski** [comment]
Related to https://github.com/SabreTools/DICUI/issues/199
