### ISSUE TITLE
DICUI doesn't add EXE/Build Date in !submissioninfo.txt

### ISSUE THREAD

**Issue by Gameboi64** [SabreTools/DICUI#202]
Been using the development builds from appveyor, and sometimes the EXE/Build Date shows up in the !submissioninfo.txt, and sometimes it doesn't. Pasting a TXT document here wouldn't do any good, as it could have been easily faked, but with all the PS1 games I've been dumping, the EXE dates haven't been showing up. Some builds it does add it, some builds it doesn't add it.

**Comment by mnadareski** [comment]
This is a bit odd to try to track down, but I'll do what I can. Has it been the same disc each time that sometimes sees it and sometimes not?

**Comment by mnadareski** [comment]
Possibly fixed by implementing INI parser in https://github.com/SabreTools/DICUI/commit/613be66f9167699306c4fdf83dce99776df72c39

**Comment by sadikyo** [comment]
I have noticed this on ps2 discs.   Here is one example:

System.CNF
BOOT2 = cdrom0:\SLPM_690.01;1.VER = 1.00.VMODE = NTSC

file in base directory = SLPM_690.01

If you need more examples, just let me know.

**Comment by mnadareski** [comment]
Please try using the newest WIP AppVeyor version and see if that still is an issue

**Comment by mnadareski** [comment]
This hasn't been marked as done by either of the people who commented on this. Can either of you check to see if this EXE date issue still exists?

**Comment by sadikyo** [comment]
I'll check on this tonight with the updated version and report back.  Thanks!

**Comment by sadikyo** [comment]
It seems to be working correctly on the latest builds I've been using, so I'm assuming this has been fixed.

**Comment by mnadareski** [comment]
Okay, unless @Gameboi64 finds otherwise, this is closed for now.
