### ISSUE TITLE
DICUI reporting incorrect layerbreak info on xbox discs

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/DICUI#203]
DICUI reports typically the layerbreak of "1715632" on xbox discs, but apparently, xbox discs should have the default layerbreak of 1913776 and that should be standard, according to Enker.  I asked him for more technical information about this, and here is what he said:

"Hey, yes the DICUI layerbreak for Xbox/Xbox360 (and also Blu-ray discs) is incorrect. It's caused by DIC reporting two layerbreaks, one for the video partition and one for the game partition (DICUI uses this one). It never logs the actual layerbreak that takes into account the video partition+middle zone that comes before the game partition. If you add the video LayerZeroSector + Middle Zone + game LayerZeroSector, then you get the default value on the disc page.

DICUI could omit the layerbreak for Xbox/Xbox360/Blu-ray discs, since we never need to enter one for those discs."

Let me know if you have any questions or need any more information! Thanks!

**Comment by mnadareski** [comment]
This should be fixed as of https://github.com/SabreTools/DICUI/commit/81e0ffbc3cce0147e0aa360fb5906c5d165c0536
