### ISSUE TITLE
4 different drives can not dump CD ROM from the 90's

### ISSUE THREAD

**Issue by Amazingsteve** [SabreTools/DICUI#204]
I have tried 4 DIFFERENT drives and 2 of which are supported. 

Not 1
Not 2 

BUT 4 different drives. 

2 of them are supported with offset. I just purchased a new drive on the offset list 4 days ago.

1. Internal drive
2. External Buffalo drive which was recommended but, could not get the proper offset. 
3. LG Electronics - DVDRAM SP80NB60
Lastly, recommended for the area for CD\s but, does not work on CD ROM's, WHY/
ASUS SDRW-08U7M-U

Proper offset and is on the list. I also found other people online using it. 

You should not need to $200 special cd drive or crazy insane hard to find external drive in order for this to work. What is the problem? Am I really not going to be able to do this? I have to buy some SUPER expensive hard to find drive? 

I get 3 different errors

Framework is updated
Version 3rd version below the newest.
CD ROM's from the 90's and 2000"s
CDFS
I think it Safeguard

I get three different errors.. 

LBA[1262496, 0x1343a0]: [F:ReadDVD][L:300]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[1262496, 0x1343a0]: [F:ReadDVD][L:300]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[1262496, 0x1343a0]: [F:ReadDVD][L:300]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[1262496, 0x1343a0]: [F:ReadDVD][L:300]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[1262496, 0x1343a0]: [F:ReadDVD][L:300]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

LBA[1262496, 0x1343a0]: [F:ReadDVD][L:300]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-11-00 = MEDIUM_ERROR - UNRECOVERED READ ERROR

.....................................................................................................................................................................................................................................................................................................................................................................................................................

LBA[149499, 0x247fb]: [F:ReadCDForCheckingReadInOut][L:644]
	Opcode: 0xbe
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 05-21-00 = ILLEGAL_REQUEST - LOGICAL BLOCK ADDRESS OUT OF RANGE
lpCmd: be, 04, 00, 02, 47, fb, 00, 00, 01, f8, 00, 00
dwBufSize: 2352

.....................................................................................................................................................................................................................................................................................................................................................................................................................

The most frequent one is:

Byte order of this drive is main + sub + c2
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 0]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 1]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 2]
This drive can read data sectors at scrambled state [OpCode: 0xbe, C2flag: 1, SubCode: 4]
Checking reading lead-out -> This drive can't read the lead-out

**Comment by mnadareski** [comment]
This is related to DiscImageCreator, not the UI. Please open an issue against that instead: https://github.com/saramibreak/DiscImageCreator
I have nothing to do with the DiscImageCreator development.
