### ISSUE TITLE
DICUI submission info box not popping up

### ISSUE THREAD

**Issue by Gameboi64** [SabreTools/DICUI#207]
In this case, the DICUI version (1.16-307 as of now) I have tried, which is tied to my first issue I submitted wherein the EXE dates were not noted, cannot be found, because every time I dump a disc, it just sits at "gathering submission information... please wait!" and does nothing for the submission information.
![unknown](https://user-images.githubusercontent.com/13713250/84811106-3884d600-afc1-11ea-8f35-b5af2feb5b5d.png)

I don't know what to do here, as there is nothing I can seem to find for all of this other than submit it as a problem. I've tried it both with the box ticked and unticked for the pop up to show up, with my login credentials, everything.

**Comment by mnadareski** [comment]
Fixed in https://github.com/SabreTools/DICUI/commit/6bda7b35a26548d0451381d33e16d438cdf7a440
