### ISSUE TITLE
DICUI & DICUI.Check does not work with latest DIC release because of a change in filename logic

### ISSUE THREAD

**Issue by tenyuhuang** [SabreTools/DICUI#208]
Using DICUI 1.16.1 with DiscImageCreator 20200620.
DIC 20200620 replaced `XXXX_cmd.txt` with `XXXX_<TIME>.txt` in the output file, which made DICUI and DICUI.Check refuse to generate `!submissioninfo.txt`. Renaming the file solves the issue.

Would you look into the issue and make changes accordingly? Thank you!

**Comment by mnadareski** [comment]
This was already addressed in the WIP builds as per https://github.com/SabreTools/DICUI/commit/95b664705deb67abfa70f2e867c32003a70857bb
