### ISSUE TITLE
DICUI submission doesn't show anymore important Xbox 360 fields

### ISSUE THREAD

**Issue by LoStraniero91** [SabreTools/DICUI#219]
I cannot pinpoint where this issue started, but since a month the DICUI submission doesn't show important Xbox 360 fields. These fields are the hashes of the stealth files (DMI, PFI and SS) and the security sectors. 
I've dumped a XGD2 Xbox 360 game with Kreon and here's the logs.

[SCENE IT_2.zip](https://github.com/SabreTools/DICUI/files/5104274/SCENE.IT_2.zip)

**Comment by mnadareski** [comment]
If I'm reading this correctly, it seems like the location (or format) of the hashes has changed in some way shape or form. I'll have to see what changed there and try for it.
