### ISSUE TITLE
DICUI does not pull EDC / Libcrypt / Anti-Mod for PS1 discs

### ISSUE THREAD

**Issue by sadikyo** [SabreTools/DICUI#222]
I'm not sure if this was an intentional change or not due to some previous errors, but the latest stable build and the appveyor wip build both, do not pull EDC or other protection data for ps1 discs.  

It will say:  EDC:  Yes/No, and it no longer generates anything for libcrypt or anti-mod.

**Comment by mnadareski** [comment]
Just a clarification, is this for discs that have a Redump match (and the user is logged in) or are these new discs (or the user is not logged in)?

**Comment by mnadareski** [comment]
Also, can you provide logs for a disc that this didn't pull correctly for?

**Comment by sadikyo** [comment]
The ones I tried, it was without me logged in.  Here are some logs:

https://cdn.discordapp.com/attachments/705884111448834100/753435806659641424/SLPM_80148.7z

I'll try another one for a verification, logged in, and share the results here.  Thanks!

**Comment by sadikyo** [comment]
Alrighty, so I logged in for another one, did a verification, and it still doesn't extract the information in the submissiontxt like before.  See below for logs:

https://cdn.discordapp.com/attachments/705884111448834100/753440341809561670/SLPS_01689.7z

Let me know if you need me to test anything else or do anything differently. 

^^ In this example, when I run superg's tool I get:
EDC: Yes
Anti-modchip: No
LibCrypt: No

**Comment by mnadareski** [comment]
To keep this up to date here's the current status:
- Found the issue with EDC checking (only checking one possible output file name)
- Anti-modchip string in output seems to have disappeared? Investigating that.
- Haven't checked libcrypt yet

**Comment by mnadareski** [comment]
Okay, found the issue with anti-mod scan. It seems DIC itself had an issue scanning for anti-mod so it just never output. This is from `_mainError.txt` for the first disc.

```
LBA[084263, 0x14927]: [F:ReadCDForScanningPsxAntiMod][L:1357]
	Opcode: 0xa8
	ScsiStatus: 0x02 = CHECK_CONDITION
	SenseData Key-Asc-Ascq: 03-02-81 = MEDIUM_ERROR - VENDOR UNIQUE ERROR
lpCmd: a8, 00, 00, 01, 49, 27, 00, 00, 00, 01, 00, 00
dwBufSize: 2048
```

**Comment by mnadareski** [comment]
Looks like the reason nothing was outputting was because the EDC failure was hosing the rest of it on output. A fix should be up soon.
