### ISSUE TITLE
Dumping process freezing at lead-in reading checking

### ISSUE THREAD

**Issue by Qwest8K** [SabreTools/DICUI#223]
When I try to dump discs by my drive ASUS BW-16D1HT (firmware 3.02), dumping process almost everytime hangs after appearing of message "Checking reading lead-in -> OK" and I should stop program through task manager.

**Comment by mnadareski** [comment]
This sounds like there could be some compatibility issue going on with the base dumping application. Please report that over in [DIC's GitHub](https://github.com/saramibreak/DiscImageCreator/issues). Unfortunately, I can't help with that sort of stuff.

**Comment by Qwest8K** [comment]
Okay, thanks.
