### ISSUE TITLE
CSS keys for encrypted DVDs - into submission info

### ISSUE THREAD

**Issue by wiggy2k** [SabreTools/DICUI#224]
at the end of a dump_CSSKey.txt file (for encrypted DVD-Video) 
is the encrypted and decrypted CSS keys for the disc.

example:

```
PlayerKey[1]: 01 AF E3 12 80
DecryptedDiscKey[020]: 16 7B 3F C0 8E
LBA:     301, Filename: VIDEO_TS.VOB, No TitleKey
LBA:     386, Filename: VTS_01_0.VOB, EncryptedTitleKey: 0B 77 76 1F D3, DecryptedTitleKey: C1 DB B5 94 24
LBA:   73129, Filename: VTS_01_1.VOB, EncryptedTitleKey: 0B 77 76 1F D3, DecryptedTitleKey: C1 DB B5 94 24
LBA:  597331, Filename: VTS_01_2.VOB, EncryptedTitleKey: 0B 77 76 1F D3, DecryptedTitleKey: C1 DB B5 94 24
```

it would be useful if this could be output to the submission info Comments section in the format:

```
VIDEO_TS.VOB No Title Key
VTS_01_0.VOB Title Key: C1 DB B5 94 24
VTS_01_1.VOB Title Key: C1 DB B5 94 24
VTS_01_2.VOB Title Key: C1 DB B5 94 24
Disc Key: 16 7B 3F C0 8E

```

**Comment by TonyLizard** [comment]
To be 100% accurate, as i've previously talked with and other mods/dumpers involved and we discussed about all this stuff that can be removed:
-Player Key is not needed
-Encrypted Disc Key is not needed
-Encrypted Title Key and the LBA position of the .vob files are not needed
So, the only data needed to be showed in the output submission.txt file is:
-Region(s) of the disc
-Copyright Protection System Type
-List of the .vob files, each one with his Decrypted Title Key
-Decrypted Disc Key
You can see an example here: http://redump.org/disc/72691/

**Comment by mnadareski** [comment]
Can either of you attach a recent version of the `_CSSKey.txt` file? I want to see if the structure still matches up at least. If it does, then I can strip out the unnecessary bits fairly easily.
