### ISSUE TITLE
[Request] Feature Suggestion for Troubleshooting

### ISSUE THREAD

**Issue by Haldrie** [SabreTools/DICUI#228]
Adding an option in the GUI to export a batch file or similar to run DIC on it's own might help to isolate issues people might help in determining if the issue they are having is with DIC or DICUI.

**Comment by mnadareski** [comment]
Since DIC itself captures the last run command line and DICUI check exists for the rest of it, I don't see an explicit need for this feature right now. If this becomes more necessary in the future (likely due to a change in DIC), then I will reconsider.
