### ISSUE TITLE
Clearing main log window prevents future logging

### ISSUE THREAD

**Issue by Whovian9369** [SabreTools/DICUI#231]
Seen in **1.17.1**

Clearing the main "Log Window" (that opens by default as the bottom half of the UI) with the "Clear" button prevents further logging from being done, essentially making the window useless after being cleared once during a dumping session.

Closing and reopening DICUI as a whole "resets" the window as expected and makes it usable again.

**Comment by mnadareski** [comment]
Since I honestly don't know how that part of the logging output code works, I'll have to defer to @Jakz to see if he can address it.

**Comment by mnadareski** [comment]
I have an idea that may not be strictly correct, but seems to work...
