### ISSUE TITLE
[Request] "No Fixed Drives" option will be better checked by default

### ISSUE THREAD

**Issue by Madroms** [SabreTools/DICUI#233]
As the title says, "No Fixed Drives" option will be better checked by default:
- most of the time, DICUI is used for optical discs
- with the new feature that let you read drives by sectors to auto-detect systems, it will be safer not to read fixed drives everytimes DICUI is launched

**Comment by mnadareski** [comment]
I do agree with this one. Since no major projects actually care about HDDs, SSDs, or other such devices, it is just confusing for most new users and frustrating for the majority of the ODD-only users.
