### ISSUE TITLE
[Request] Adding a checkbox to not use subdump everytime

### ISSUE THREAD

**Issue by Madroms** [SabreTools/DICUI#234]
For Sega Saturn dump: could you add a checkbox to let the user choose if he wants to launch subdump or not.
It is useful, but not for all the dumps. and it give too much stress to the ODD, and takes a lot of time.

Also DICUI gives user the ability to change inputs when subdump is still running, so not safe. (But it is the same with other tools launched, DICUI does not wait for a callback from them, as they de not give one.)

**Comment by sadikyo** [comment]
+1.  I agree with this.  I get many many questions about the subdump run after saturn (for new users or users dumping saturn for the first time) and it often gives them many problems, doesn't work, and does put a lot of stress on the drive.  

I know they can close it mid-way, but they may not know that, so often someone will let it run for a long time, message me thinking something is broken, and we have to have the whole discussion.

**Comment by mnadareski** [comment]
Honestly, based on conversations in Discord and elsewhere, I will likely just rip out subdump entirely. It's caused too many issues and is only useful in a very small set of circumstances. I will continue to *bundle* subdump with the program, but it will not be wired up anymore.

**Comment by mnadareski** [comment]
Sometimes the best move is not to play.
