### ISSUE TITLE
[Problem] Scanning discs on all other drives when selecting only 1 drive

### ISSUE THREAD

**Issue by Madroms** [SabreTools/DICUI#235]
I have 3 ODDs: F, G, H
Only F has a CD in it.
when I select G or H Drives (Drive Letter option), DICUI still rescans the CD on Drive F every time I change the Drive Letter.
DICUI must scan the disc that is inserted on the selected drive, not on all the others.

If it matters:
F is USB
G and H are SATA

**Comment by mnadareski** [comment]
I doubt it scans "all other drives", rather, whatever the last drive that was in the set dump environment. The type of the drive won't matter here, I just have to make sure the value is taken from the UI and not the potentially outdated environment.

**Comment by mnadareski** [comment]
I'm also somewhat assuming you mean the copy protect scan from the UI, not the post-dump step. Because that's what I'm going to look at fixing.
