### ISSUE TITLE
[Problem] Skip Type Detect -> unable to choose Drive Speed except 1

### ISSUE THREAD

**Issue by Madroms** [SabreTools/DICUI#237]
With "Skip Type Detect" option checked, I am unable to scan for disks and dump.

The button "scan for disks" gives "Trying to detect system for drive F.. unable to detect."
System/Media Type is selected.
Drive Letter is selected.
As Scan for disks gives "Trying to detect system for drive F.. unable to detect.", DICUI does let you only choose Drive Speed = 1.
(Parameters is then populated after selecting Drive Speed = 1, as expected I assume)

**Comment by mnadareski** [comment]
I honestly think you're the first person to check that option. Either way, my solution is going to be to default to CD-ROM as a reasonable default so that the rest of the UI doesn't lock up.
