### ISSUE TITLE
[Request] Splitting Options config file

### ISSUE THREAD

**Issue by Madroms** [SabreTools/DICUI#238]
As DICUI.exe.Config is part of the distribution files, your own options saved are replaced with the defaults one when you update your DICUI install.
2 config files will be better:
- a default one
- a user specific one

Or no config file available with the distribution of DICUI, the config file could be generated with the first use of the program. And when the program is updated, the new version checked if an old config file exists and updates it with newly added options (so you may add the DICUI version that generated the config file, as a parameter written inside it.

**Comment by mnadareski** [comment]
I know what you're asking for, even if you didn't ask it in the way I expected. The actual fix for this is to stop including the config file by default and have it generate so it doesn't overwrite for *cough* careless users on upgrade.
