### ISSUE TITLE
Check Against Redump

### ISSUE THREAD

**Issue by mnadareski** [SabreTools/DICUI#57]
Inspired by Cleanrip being able to check against known hashes, either allow checking against a folder of datfiles OR search on the Redump site. The former relies on the users more (an may not be preferred because of that). The latter may end up causing issues with Redump and potentially would have issues with logging into the site for access, though it would be the most up to date at any point.

**Comment by Jakz** [comment]
This is why an API would be nice, since having a short json response would be surely better than having to scrape an HTML page (heavy to generate, heavy to parse). We're going back to my initial criticisms of which you know.

**Comment by einstein95** [comment]
To login to Redump, post the following data to `http://forum.redump.org/login/`
```python
{
    'form_sent': '1',
    'redirect_url': 'http://forum.redump.org/login/',
    'csrf_token': '[taken from page]',
    'req_username': '[username]',
    'req_password': '[password]',
    'save_pass': '1',
    'login': 'Login'
}
```
This gives you `redump_cookie`, use on the site for hidden dats

**Comment by mnadareski** [comment]
Something similar to this functionality has been worked on in another project. It can probably be adapted to what's needed. Self-assigning because of this.

**Comment by mnadareski** [comment]
This was basically added in https://github.com/SabreTools/DICUI/commit/27873772500221c73dfd0a2cdb7017bb09230dc9 after like... half a year of waiting. Also forgot about this issue entirely hence it wasn't closed when the actual work went in. Oops.
